---
title: "Random Forest"
author: "Navin Lo"
date: "2024-03-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
load("modeling-setup.rda")
```

```{r}
team_rf = rand_forest(mtry = tune(),
                          trees = tune(),
                          min_n = tune()) %>%
                          set_mode('classification') %>% 
                          set_engine('ranger', importance = "impurity")

rf_grid = grid_regular(mtry(range= c(1, 19)), 
                               trees(range = c(100,800)), 
                               min_n(range = c(10,20)), 
                               levels = 5)

team_rf_workflow = workflow() %>% add_model(team_rf) %>% add_recipe(team_recipe)
```

```{r}
tune_team_rf = tune_grid(
  team_rf_workflow,
  resamples = team_folds,
  grid = rf_grid
)
```

```{r}
best_rf = select_best(tune_team_rf, metric = 'roc_auc')

show_best(tune_team_rf, metric = 'roc_auc')
final_rf = finalize_workflow(team_rf_workflow, best_rf)
final_rf = fit(final_rf, team_train)
```

```{r}
save(tune_team_rf, best_rf, final_rf, file = "TeamRandomForest.rda")
```

